# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9103eb43311167761c93a59fa3e43b73ba35890952d5319acaec830be9c3149dbc0be3b12d626d1e8280a925815df7f9b203955c8163725c4658cdff2f026492

test:
  secret_key_base: 1a294b183b304a4593eb58c6eea30cc77458d59327742ea1f27edb738e2abca9f3ab22a9e47af4bf13fb551227cabfab0a4db6fd87e7fb2e9fd672cafc8902db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
